<a href="https://colab.research.google.com/github/Annamjohn/Numpy/blob/main/arithmetic%20ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([(1,2,3),(3,4,5)])

b=np.array([(1,2,3),(3,4,5)])
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[[ 2  4  6]
 [ 6  8 10]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [ 9 16 25]]
[[1. 1. 1.]
 [1. 1. 1.]]
