<a href="https://colab.research.google.com/github/Annamjohn/Numpy/blob/main/concatenation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
#vertical stack(concatenation)
import numpy as np
a=np.array([(1,2,3),(3,4,5)])

b=np.array([(1,2,3),(3,4,5)])
print(np.vstack((a,b)))

[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]


In [42]:
#horizontal stack(concatenation)
import numpy as np
a=np.array([(1,2,3),(3,4,5)])

b=np.array([(1,2,3),(3,4,5)])
print(np.hstack((a,b)))

[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]
