<a href="https://colab.research.google.com/github/Annamjohn/Numpy/blob/main/exp%20and%20log.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#exponent

[ 2.71828183  7.3890561  20.08553692]


In [3]:
#natural log
import numpy as np
import matplotlib.pyplot as plt
a=np.array([1,2,3])
print(np.log(a))

[0.         0.69314718 1.09861229]


In [4]:
import numpy as np
import matplotlib.pyplot as plt
a=np.array([1,2,3])
print(np.log10(a))

[0.         0.30103    0.47712125]
